import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'kotlin-parcelize'
}

android {
    compileSdk = 35
    ndkVersion = "28.2.13676358"

    defaultConfig {
        minSdk = 24
        targetSdk = 35

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    namespace = 'org.openedx.auth'

    flavorDimensions += "env"
    productFlavors {
        prod {
            dimension = 'env'
        }
        develop {
            dimension = 'env'
        }
        stage {
            dimension = 'env'
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget("17")
            freeCompilerArgs.addAll(List.of("-Xstring-concat=inline"))
        }
    }
    buildFeatures {
        viewBinding = true
        compose = true
    }
}

dependencies {
    implementation project(path: ':core')

    // AndroidX
    implementation "androidx.browser:browser:$browser_version"
    implementation "androidx.credentials:credentials:$credentials_version"
    implementation "androidx.credentials:credentials-play-services-auth:$credentials_version"

    // Social Login
    implementation "com.facebook.android:facebook-login:$facebook_login_version"
    implementation "com.google.android.gms:play-services-auth:$play_services_auth_version"
    implementation "com.google.android.libraries.identity.googleid:googleid:$googleid_version"
    implementation("com.microsoft.identity.client:msal:$msal_version") {
        exclude group: 'com.microsoft.identity.client', module: 'msal-browser'
        exclude group: 'io.opentelemetry', module: 'opentelemetry-bom'
    implementation "androidx.credentials:credentials:1.3.0"
    implementation "androidx.credentials:credentials-play-services-auth:1.3.0"
    implementation "com.facebook.android:facebook-login:18.0.2"
    implementation "com.google.android.gms:play-services-auth:21.3.0"
    implementation "com.google.android.libraries.identity.googleid:googleid:1.1.1"
    implementation("com.microsoft.identity.client:msal:4.9.0") {
        //Workaround for the error Failed to resolve: 'io.opentelemetry:opentelemetry-bom' for AS Iguana
        exclude(group: "io.opentelemetry")
    }

    // OpenTelemetry
    implementation("io.opentelemetry:opentelemetry-api:$opentelemetry_version")
    implementation("io.opentelemetry:opentelemetry-context:$opentelemetry_version")

    testImplementation "junit:junit:$junit_version"
    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation "androidx.arch.core:core-testing:$android_arch_version"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlinx_coroutines_test_version"
    androidTestImplementation "androidx.test.ext:junit:$test_ext_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso_version"
}
