import org.jetbrains.kotlin.gradle.dsl.JvmTarget

def config = configHelper.fetchConfig()
def appId = config.getOrDefault("APPLICATION_ID", "org.openedx.app")
def platformName = config.getOrDefault("PLATFORM_NAME", "OpenEdX")
def themeDirectory = config.getOrDefault("THEME_DIRECTORY", "openedx")
def firebaseConfig = config.get('FIREBASE')
def firebaseEnabled = firebaseConfig?.getOrDefault('ENABLED', false)
def datadog = config.get("DATADOG") ?: [:]

apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'kotlin-parcelize'
apply plugin: 'com.google.devtools.ksp'

if (firebaseEnabled) {
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'com.google.firebase.crashlytics'

    tasks.register('generateGoogleServicesJson') {
        configHelper.generateGoogleServicesJson(appId)
    }

    preBuild.dependsOn(generateGoogleServicesJson)
} else {
    tasks.register('removeGoogleServicesJson') {
        configHelper.removeGoogleServicesJson()
    }

    preBuild.dependsOn(removeGoogleServicesJson)
}

android {
    compileSdk = 36
    ndkVersion = "28.2.13676358"

    defaultConfig {
        applicationId = appId
        minSdk = 24
        targetSdk = 36
        versionCode =  6003001
        versionName =  "6.3.1"

        resourceConfigurations += ["en", "uk"]

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    namespace = 'org.openedx.app'

    flavorDimensions += "env"
    productFlavors {
        prod {
            dimension = 'env'
            setupBranchConfigFields(it)
            setupFirebaseConfigFields(it)
    }
        develop {
            dimension = 'env'
            setupBranchConfigFields(it)
            setupFirebaseConfigFields(it)
    }
        stage {
            dimension = 'env'
            setupBranchConfigFields(it)
            setupFirebaseConfigFields(it)
    }
    }
    productFlavors.all { flavor ->
        flavor.buildConfigField "boolean", "DD_ENABLED",
                "${datadog.getOrDefault("ENABLED", false)}"

        flavor.buildConfigField "String", "DD_ENV",
                "\"${datadog.getOrDefault("DATADOG_ENVIRONMENT", "stage")}\""

        flavor.buildConfigField "String", "DD_CLIENT_TOKEN",
                "\"${datadog.getOrDefault("DATADOG_CLIENT_TOKEN", "")}\""

        flavor.buildConfigField "String", "DD_APPLICATION_ID",
                "\"${datadog.getOrDefault("DATADOG_APPLICATION_ID", "")}\""
    }
    sourceSets {
        prod {
            res.srcDirs += ["src/$themeDirectory/res"]
        }
        develop {
            res.srcDirs += ["src/$themeDirectory/res"]
        }
        stage {
            res.srcDirs += ["src/$themeDirectory/res"]
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            if (firebaseEnabled) {
                firebaseCrashlytics {
                    mappingFileUploadEnabled = true
                }
            }

            // Only apply release signing configurations if keystore.properties is available
            if (project.file("signing/keystore.properties").exists()) {
                apply from: "signing/signing.gradle"

                applicationVariants.all { variant ->
                    variant.outputs.all { output ->
                        output.outputFileName = "${platformName}-${variant.buildType.name}-v${versionName}.apk"
                    }
                }
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget("17")
            freeCompilerArgs.addAll(List.of("-Xstring-concat=inline"))
        }
    }
    buildFeatures {
        viewBinding = true
        compose = true
        buildConfig = true
    }
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(path: ':core')
    implementation project(path: ':auth')
    implementation project(path: ':course')
    implementation project(path: ':dashboard')
    implementation project(path: ':discovery')
    implementation project(path: ':profile')
    implementation project(path: ':discussion')
    implementation project(path: ':whatsnew')
    implementation project(path: ':notifications')
    implementation project(path: ':featuremanagement')

    ksp "androidx.room:room-compiler:$room_version"

    implementation 'androidx.core:core-splashscreen:1.0.1'

    api platform("com.google.firebase:firebase-bom:$firebase_version")
    api "com.google.firebase:firebase-messaging"

    // Segment Library
    implementation "com.segment.analytics.kotlin:android:1.16.3"
    // Segment's Firebase integration
    implementation 'com.segment.analytics.kotlin.destinations:firebase:1.5.6'
    // Braze SDK Integration
    implementation "com.braze:braze-segment-kotlin:1.4.2"
    implementation "com.braze:android-sdk-ui:30.2.0"
    // Datadog SDK Integration
    implementation "com.datadoghq:dd-sdk-android-rum:3.6.0"
    implementation "com.datadoghq:dd-sdk-android-logs:3.6.0"
    implementation "com.datadoghq:dd-sdk-android-trace:3.6.0" // optional
    implementation "com.datadoghq:dd-sdk-android-webview:3.6.0" // if using WebView
    implementation "com.datadoghq:dd-sdk-android-okhttp:3.6.0"

    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
    testImplementation "junit:junit:$junit_version"
    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation "io.mockk:mockk-android:$mockk_version"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines_version"
    testImplementation "androidx.arch.core:core-testing:$android_arch_version"
}

private def setupBranchConfigFields(buildType) {
    def branchConfig = configHelper.fetchConfig().get("BRANCH")
    def branchKey = ""
    def branchUriScheme = ""
    def branchHost = ""
    def branchAlternateHost = ""

    if (branchConfig && branchConfig.get("ENABLED")) {
        branchKey = branchConfig.getOrDefault("KEY", "")
        branchUriScheme = branchConfig.getOrDefault("URI_SCHEME", "")
        branchHost = branchConfig.getOrDefault("HOST", "")
        branchAlternateHost = branchConfig.getOrDefault("ALTERNATE_HOST", "")

        // Validation: Throw exception if any field is empty
        if (branchKey.isEmpty() || branchUriScheme.isEmpty() || branchHost.isEmpty() ||
                branchAlternateHost.isEmpty()) {
            throw new IllegalStateException("One or more Branch configuration fields are empty.")
        }
    }

    buildType.resValue "string", "branch_key", branchKey
    buildType.resValue "string", "branch_uri_scheme", branchUriScheme
    buildType.resValue "string", "branch_host", branchHost
    buildType.resValue "string", "branch_alternate_host", branchAlternateHost
}

private def setupFirebaseConfigFields(buildType) {
    def firebaseConfig = configHelper.fetchConfig().get('FIREBASE')
    def firebaseEnabled = firebaseConfig?.getOrDefault('ENABLED', false)
    def cloudMessagingEnabled = firebaseConfig?.getOrDefault('CLOUD_MESSAGING_ENABLED', false)

    buildType.manifestPlaceholders = [fcmEnabled: firebaseEnabled && cloudMessagingEnabled]
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}
