import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'kotlin-parcelize'
    id 'com.google.devtools.ksp'
}
def config = rootProject.ext.configHelper.fetchConfig()
def datadog = config.get("DATADOG") ?: [:]
def discovery = config.get("DISCOVERY") ?: [:]
def discoveryWebView = discovery.get("WEBVIEW") ?: [:]

android {
    compileSdk = 36
    ndkVersion = "28.2.13676358"

    defaultConfig {
        minSdk = 24
        targetSdk = 36

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        buildConfigField "String", "DISCOVERY_TYPE",
                "\"${discovery.getOrDefault("TYPE", "webview")}\""

        buildConfigField "String", "DISCOVERY_BASE_URL",
                "\"${discoveryWebView.getOrDefault("BASE_URL", "")}\""

        buildConfigField "String", "DISCOVERY_COURSE_DETAIL_TEMPLATE",
                "\"${discoveryWebView.getOrDefault("COURSE_DETAIL_TEMPLATE", "")}\""

        buildConfigField "String", "DISCOVERY_PROGRAM_DETAIL_TEMPLATE",
                "\"${discoveryWebView.getOrDefault("PROGRAM_DETAIL_TEMPLATE", "")}\""


    }

    namespace = 'org.openedx.discovery'

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget("17")
            freeCompilerArgs.addAll(List.of("-Xstring-concat=inline"))
        }
    }

    buildFeatures {
        viewBinding = true
        compose = true
        buildConfig = true
    }

    flavorDimensions += "env"
    productFlavors {
        prod {
            dimension = 'env'
        }
        develop {
            dimension = 'env'
        }
        stage {
            dimension = 'env'
        }
    }
}

dependencies {
    implementation project(path: ':core')

    ksp "androidx.room:room-compiler:$room_version"
    implementation 'androidx.activity:activity-compose:1.8.1'

    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
    testImplementation "junit:junit:$junit_version"
    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation "io.mockk:mockk-android:$mockk_version"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines_version"
    testImplementation "androidx.arch.core:core-testing:$android_arch_version"
    // Datadog DSK Integration
//    implementation("com.datadoghq:dd-sdk-android:2.0.0")
    implementation "com.datadoghq:dd-sdk-android-rum:3.6.0"
    implementation "com.datadoghq:dd-sdk-android-logs:3.6.0"
    implementation "com.datadoghq:dd-sdk-android-trace:3.6.0" // optional
    implementation "com.datadoghq:dd-sdk-android-webview:3.6.0" // if using WebView

}
